### ISSUE TITLE
logins.sh failing with SqliteError: no such table: Rings

### ISSUE THREAD

**Issue by ryanfantus** [theflyingape/dankdomain#1]
Hi,

I'm trying to host dankdomain myself but am running into issues. I should mention I'm on 64 bit debian sid. I followed all the steps in install.sh and got the service to run with systemd. Everything appears to be fine. However, when I try to telnet in, launching the `logins.sh` script, I get the following errors:

```root@dankdomain:/etc/xinetd.d# telnet localhost
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
[_BAR]
?Unexpected SQL error: SqliteError: no such table: Rings -- retrying

?Unexpected SQL error: SqliteError: no such table: Rings -- retrying

?Unexpected SQL error: SqliteError: no such table: Rings
?FATAL SQL operation: UPDATE Rings set bearer = "" WHERE name = "Atomic"Connection closed by foreign host.
```

Do I need to manually create this table somewhere? And how do I do so?

Thanks!

**Comment by theflyingape** [comment]
Thanks for reporting this failure, @ryanfantus , the Rings table is initialized too far down a new installation and thus any NPC armed with a ring causes this to fail.  I will fix this ASAP.

**Comment by theflyingape** [comment]
If possible, just drop the SQLite file: `rm users/dankdomain.sql`
and re-run the install please.

**Comment by ryanfantus** [comment]
Yep! Rebuilt and have moved past this one, good to go! Thanks.
