### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by xrpdevs** [theflyingape/dankdomain#11]
Can't install fxvt (401 error)

The docker pull command isn't working for me either.

**Comment by xrpdevs** [comment]
Was able to get fxvt working by manually downloading from your github repo and building...

**Comment by xrpdevs** [comment]
I'm using the latest Ubuntu, by the way. The installer script doesn't work properly without changes.
I shall clone the repo here and put in my changes and a pull request once I get it working properly.

A real blast from the past!! :)

**Comment by theflyingape** [comment]
Sure, the **xvt** package dependency to the github repository is no longer working?  The "f' you keep referencing is part of %2f encoding for "/".  Clearly, something got borked publishing to the GitHub repository.

That can be overridden by removing the `@theflyingape` scope in its package.json and have it default back to the NPM public repository, where it's published too.
