### ISSUE TITLE
npm install failing on dependency @theflyingape/xvt@^1.4.6

### ISSUE THREAD

**Issue by ryanfantus** [theflyingape/dankdomain#12]
Hello,

On a fresh Ubuntu 20.04 with node v16.2.0, npm v7.14.0, with a fresh clone of this repo, I can't run 'install.sh' since it clearly depends on fedora, but attempting a manual install currently fails as well. 'npm install' in the root of the project results in the following error:

```~/dankdomain$ npm install
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR!
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login
```

According to logs, it looks like package `@theflyingape/xvt` is either private or requires some sort of authentication to install. Can you please advise? Thanks!

**Comment by theflyingape** [comment]
Yup, you got it.  Feel free to remove package scope -- it's maintained in both repositories with Public access.
Onward.
