### ISSUE TITLE
Bank depositing bug

### ISSUE THREAD

**Issue by ryanfantus** [theflyingape/dankdomain#3]
When visiting the bank and using 'D' to deposit money, if you just hit "enter" and fail to specify a deposit amount, nothing gets deposited and all money on hand is lost.

**Comment by theflyingape** [comment]
Cannot reproduce and could not hunt down any root cause in square.ts source history.  I suspect you got caught in the crossfire by a large internal refactoring effort, necessitating a development branch this past month.  I merged that branch today back into the master.  Please upgrade.  :)
