### ISSUE TITLE
Dungeon Thief does not appear in dungeon

### ISSUE THREAD

**Issue by Boneill3** [theflyingape/dankdomain#4]
It looks like the dungeon thief icon is not appearing (with a marauders map). It should be an & symbol according to the documentation. 

<img width="751" alt="Screen Shot 2020-03-19 at 4 15 56 PM" src="https://user-images.githubusercontent.com/4459604/77123775-52cd0900-69fe-11ea-9e70-84b41c7e22f3.png">

**Comment by Boneill3** [comment]
Maybe it's an issue with the documentation? 
![image](https://user-images.githubusercontent.com/4459604/77123927-b3f4dc80-69fe-11ea-9995-cace8896aa93.png)

![image](https://user-images.githubusercontent.com/4459604/77123946-c1aa6200-69fe-11ea-9d6e-6292274ae996.png)

Actually, I don't know if the box with an x is the same as an open box.

**Comment by theflyingape** [comment]
@Boneill3 can you detail me which OS/browser/version you are using?  This emulator (https://github.com/xtermjs/xterm.js) is configured to make use of **Unicode 11** characters.  I find it works well with Chromium-based browsers, Chrome & Edge, and from Linux terminal apps gnome-terminal and terminology.

The dungeon thief symbol used is ⚷ - astrology Chiron -- see https://en.wiktionary.org/wiki/%E2%9A%B7

I see your wishing well does not render ⛃ either - the black checkers king - see  https://en.wiktionary.org/wiki/%E2%9B%83

You can try switching your emulation mode to 'VT' (old school) from the Main Menu - User options.  Enjoy!

**Comment by Boneill3** [comment]
It definitely relates to Mac OS (Catalina). I can't see those icons on both safari and chrome even in your text above or the wiktionary page. 

Looking at it on Firefox running on a Ubuntu 18.04.4 LTS system, it looks fine.

I'll try to find a resolution on the Mac side.

**Comment by Boneill3** [comment]
So I was able to fix it in chrome on Mac OS by installing the gnu unifont, but it's still not working in safari. Also, I was only able to test on the ddgame.us site, not in the game.

It also worked for me in windows running edge, but some of the icons looks a little different. Maybe it would make sense to force a font using font-face in the css? 
https://www.w3schools.com/cssref/css3_pr_font-face_rule.asp

**Comment by theflyingape** [comment]
Sure, doing that already with 'tty'. I bundled the game with the Google Noto fonts with color emoji support.  See if that helps your Mac, thanks.

**Comment by theflyingape** [comment]
Removed all Noto fonts from C:\Windows\Fonts and remote tested updated stylesheets.
