### ISSUE TITLE
Is it because I'm an awesome Titan?

### ISSUE THREAD

**Issue by mcmlxxix** [theflyingape/dankdomain#7]
+------------------=:)) Mcmlxxix ((:=------------------+
(node:102335) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Character.stats (/usr/local/games/dankdomain/common.js:203:67)
    at Object.cb (/usr/local/games/dankdomain/tty/main.js:397:34)
    at session.<anonymous> (/usr/local/games/dankdomain/node_modules/xvt/xvt.js:229:19)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/games/dankdomain/node_modules/xvt/xvt.js:5:58)
(node:102335) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:102335) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
WebSocket close

**Comment by theflyingape** [comment]
Yikes, what's this?  I am deducing you don't have anything out of the ordinary to add, i.e., was your character morphed?

Wait, I just looked at your character record, and is shows me you have  "access": "Marchioness", but your sex & gender are "M".  That's not right, so I mam guessing you the promotion from rolling as "F" got you this title, but the reroll reverts character gender back to your sex ... I'll repair this to "Marquess" (Your Lordship) and return your call.

Oct 21 18:22:35 ddgame ddgame[71054]: Player (MCM) updated: 1

And, yes, you are awesome... so I also gave you a blessing.  ;)
